# Generated by Django 3.2.6 on 2021-08-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snipped',
            new_name='Snippet',
        ),
    ]
